```{r}
library(readxl)
library(openxlsx)
library(tidyverse)
library(here)

# Reading in the data from the "Ship data by record ID" and "Bird data by record ID" sheets and setting as two seperate variables

ship_data <- read_excel(here("1_raw_data/seabirds.xls"), sheet = "Ship data by record ID")

bird_data <- read_excel(here("1_raw_data/seabirds.xls"), sheet = "Bird data by record ID")

# Joining both data sets together

seabird_data <- left_join(ship_data, bird_data, "RECORD ID")

seabird_data

```

```{r}

names(seabird_data)

# Selecting the relevant columns for analysis
seabird_data_cleaned <- seabird_data %>%
  select(
    "RECORD ID", 
    "Species common name (taxon [AGE / SEX / PLUMAGE PHASE])", 
    "Species  scientific name (taxon [AGE /SEX /  PLUMAGE PHASE])", 
    "Species abbreviation", 
    "COUNT", 
    "LAT"
    ) %>%
  
  # renaming column names to better naming conventions
  rename(
    record_id = "RECORD ID", 
    species_common_name =  "Species common name (taxon [AGE / SEX / PLUMAGE PHASE])",
    species_scientific_name = "Species  scientific name (taxon [AGE /SEX /  PLUMAGE PHASE])",
    species_abbreviation = "Species abbreviation",
    total_birds_counted = "COUNT",
    latitude = "LAT"
    ) %>%
  
  # Removing [NO BIRDS RECORDED] values
  filter(species_common_name != "[NO BIRDS RECORDED]")
  
```


```{r}
write_csv(seabird_data_cleaned, here("/3_clean_data/seabird_data_clean.csv"))
```







