
```{r}

# Reading in decatholon data

library(readr)
library(here)
library(tidyverse)

here::here()

decathlon_data <- read_rds(here("1_raw_data/decathlon.rds"))


```


```{r}

# Reviewing dimensions of decathlon data

dim(decathlon_data)

```

```{r}
# Review variable names of decathlon data

names(decathlon_data)
```

```{r}
# Reviewing structure of decathlon data

head(decathlon_data, 10)
```

```{r}
tail(decathlon_data, 10)
```

```{r}
# Eyeballing data
view(decathlon_data)
```

```{r}
library(janitor)

# cleaning data

decathlon_data_clean <- clean_names(decathlon_data) %>% # Cleaning column names
  rownames_to_column(var = "athlete_names") %>% # Moving row of names to a seperate column called "athlete_names"
  rename(total_points = points) %>% #Renaming "points" to "total_points"
  mutate(athlete_names = str_to_lower(athlete_names)) %>% #Converting all names to lowercase
  pivot_longer(cols = c("x100m", "x400m", "long_jump", "shot_put"),
             names_to = "event",
             values_to = "time_distance") %>% #Pivoting the data into long format
  select(athlete_names, event, time_distance, total_points, competition) #Selecting only the rows necessary for the analysis questions in 1.1.2
  
```

```{r}
# Writing cleaned Decathlon data to CSV

write_csv(decathlon_data_clean, here("/3_clean_data/clean_decathlon_data.csv"))
```



